# makefile for the 321db project
# Author: Matthew A. Terry
# Date created: 10/11/25
# =============================================================================
# Macro definitions

# general target
all:

# cleanup target
clean:
	cd lib; \
	rm *.o; \
	rm *.a; \
	rm *.so; \
	cd ..; \
	rm 321db
