
CREATE TABLE S (
	 SNO	VARCHAR2(3)	CONSTRAINT pk_S PRIMARY KEY 
	,SNAME VARCHAR2(10)
	,STATUS NUMBER(5)
	,CITY VARCHAR2(10)
);


CREATE TABLE P (
	 PNO	VARCHAR2(3)	CONSTRAINT pk_P PRIMARY KEY 
	,PNAME VARCHAR2(10)
	,COLOR VARCHAR2(5)
	,WEIGHT DECIMAL(5,2)
	,CITY VARCHAR2(10)
);


CREATE TABLE SP (
	 SNO	VARCHAR2(3)	 
	,PNO	VARCHAR2(3)	 
	,QTY  NUMBER(3)
,CONSTRAINT pk_SP PRIMARY KEY(SNO,PNO)
,CONSTRAINT fk_SNO_in_S FOREIGN KEY(SNO) REFERENCES S(SNO)
,CONSTRAINT fk_PNO_in_P FOREIGN KEY(PNO) REFERENCES P(PNO)
);




